version: 2
jobs:
buildingTheFrontEnd:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo/FrontEnd
steps:
      - checkout:
        path: ~/repo
      
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: yarn install
   
      - save_cache:
        paths:
          - node_modules
          - ~/.npm 
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}
    
      - run: yarn test


version: 2
jobs:
  buildingTheBackEnd:

    working_directory: ~/repo/BackEnd

    docker:
      - image: circleci/postgres:9.6.3-alpine
      - image: circleci/openjdk:11-jdk-stretch

      environment:
        ports: '5432'
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: sept_project
    
    steps:
      - checkout:
        path: ~/repo

      - replaceCache:
        key: circleci-backend-java-spring-{{checksum "pom.xml"}}
      
      - run: mvn dependency:go-offline

      - saveCache:
          paths:
            - ~/.m2
          key: circleci-backend-java-spring-{{checksum "pom.xml"}}

      - run: mvn test
      - run: mvn package


workflows:
  version: 2

  buildBack&FrontEnd:
    jobs: 
      - buildingTheFrontEnd
      - buildingTheBackEnd